Project 1 Cleaning Stuffs

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("G:/YEAR 1/SEMESTER 1/DATA1001/Coding Stuff/Datasets/Project 1/data1001_survey_data.csv")

In [ ]:
df.head()
df.info()
df.describe()

In [4]:
# Removing the blank spaces on the two sides of the columns' name (since it exists in the original file)
df.columns = df.columns.str.strip()

# The process of cleaning up the "Country_of_birth" column
df.rename(columns={"country_of_birth _5_TEXT":"COB",
                   "si_1":"stress_level",
                   }, inplace=True)
df["COB"] = df['COB'].fillna(df["country_of_birth"])
df['COB'] = df['COB'].replace({
    'Viet Nam': 'Vietnam',
    'Republic Of Korea': 'South Korea',
    'Republic Of China (Taiwan)': 'Taiwan',
    'Hong Kong Sar': 'Hong Kong',
    'Nz': 'New Zealand',
    'Uk': 'United Kingdom',
    'Uae': 'United Arab Emirates',
    "Viá»‡t Nam": "Vietnam",
    "Korea": "South Korea",
    "England": "United Kingdom"
})

# General cleaning, such as dropping duplicates, removing "unrealistic" rows, etc.
df = df.drop_duplicates()
df = df.drop(index=[163,85])
df = df.drop(index=df[df["COB"] == "Other Please Specify"].index)
df = df.drop(index=df[df["rent"] > 5000].index)

# Dropping unrelated/valueless columns
df = df.drop(columns = "consent")
df = df.drop(columns=['Progress','country_of_birth'])

# Dropping all rows with blank value(s) in numeric columns
numeric_columns = df.select_dtypes(include=['number']).columns
df = df.dropna(subset=numeric_columns)

# Resetting the index after cleaning
df.index.name = "student_no"
df = df.reset_index()
df.drop(columns="student_no", inplace = True)

In [5]:
df

,age,gender,COB,hours_work,social_media_use,rent,friends_count,stress_level,highest_speed,relationship_status,...,student_type,mainstream_advanced,semesters,commute,data_interest _1,mark_goal,hours_studying,lecture_mode,study_type,learner_style
0,20.0,Female,Singapore,0.0,10.15,378.0,5.0,7.0,100.0,Single,...,International,DATA1001,1.0,3.0,3.0,80.0,2.0,Lecture Slides,I leave things to the last minute,Style 2
1,18.0,Female,Indonesia,0.0,3.47,549.0,15.0,2.0,120.0,Single,...,International,DATA1901,0.0,10.0,7.0,70.0,5.0,I,I work steadily all semester,Style 3
2,20.0,Female,China,160.0,1.12,0.0,2.0,5.0,130.0,Its complicated,...,Domestic,DATA1001,4.0,75.0,4.0,85.0,5.0,Lecture Slides,I work steadily all semester,Style 3
3,19.0,Male,Australia,1.0,23.99,0.0,0.0,0.0,200.0,Married,...,Domestic,DATA1901,20.0,1.0,0.0,100.0,60.0,Lecture Slides,I leave things to the last minute,Style 3
4,18.0,Male,Vietnam,0.0,1.00,300.0,6.0,3.0,120.0,Single,...,International,DATA1001,0.0,90.0,7.0,85.0,4.0,I,I work steadily all semester,Style 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,19.0,Female,Japan,0.0,4.19,600.0,16.0,7.0,0.0,Single,...,International,DATA1001,1.0,3.0,8.0,95.0,4.0,I,It changes depending on the subject,Style 2
514,22.0,Male,Denmark,0.0,1.50,370.0,25.0,1.0,245.0,Single,...,International,DATA1001,4.0,15.0,8.0,90.0,5.0,Recording,I work steadily all semester,Style 3
515,18.0,Male,Mongolia,0.0,7.75,0.0,25.0,7.0,150.0,In a relationship,...,International,DATA1001,0.0,10.0,8.0,100.0,6.0,I,I work steadily all semester,Style 3
516,18.0,Female,Malaysia,1.0,1.50,354.0,7.0,5.0,120.0,Single,...,Domestic,DATA1001,1.0,15.0,1.0,92.0,3.0,Recording,I work steadily all semester,Style 3
517,20.0,Male,China,30.0,6.00,2000.0,4.0,6.0,120.0,Single,...,International,DATA1001,1.0,10.0,3.0,65.0,15.0,Live Stream from Lecture Theatre,It changes depending on the subject,Style 3

In [7]:
df.to_csv("Data1001Survey_Cleaned.csv")